### ISSUE TITLE
Linkek kattinthatósága

### ISSUE THREAD

**Issue by ShrekhavingabadDay** [simonyiszk/g7-web-frontend#1]
Tisztelt Fejlesztők!

Jó volna, ha a "hírek" oldalon található legfrissebb hírben szereplő linkek "a" tagekként lennének renderelve, hogy a másolás és beillesztés fáradságos folyamata helyett a böngésző kattintásra elvégezze a piszkos munkát.

Köszönettel:
Egy felhasználó

**Comment by AndrisBorbas** [comment]
1.1.6 ban hozzá lett adva, nemsokára live lesz.

**Comment by Gerviba** [comment]
`1.1.6` live, backendből ma este megy ki az `1.0.20` az fixeli a hírek sorrendjés issuet is
